
all::
	@echo "To build this tool, you must build the transactiondb and the pipe_view/core componets:"
	@echo "    cd transactiondb; mkdir build; cd build; cmake .. -DSPARTA_BASE=/path/to/sparta; make"
	@echo "    cd pipe_view/core; make"
